[202511][ci] use correct slave container for each branch (#1746)
* update docker slave name

Signed-off-by: yijingyan2 <yijingyan@microsoft.com>

* Fix sonic-vpp build issue in master

### why
compilation of sonic-vpp failed with below error.

In file included from vpp/SwitchVpp.h:8,
                 from VirtualSwitchSaiInterface.cpp:19:
vpp/TunnelManager.h:104:32: error: field 'm_router_mac' has incomplete type 'std::array<unsigned char, 6>'
  104 |         std::array<uint8_t, 6> m_router_mac;

### what this PR does
Add missing include.

### how it is verified
sonic-vpp build is successful with the fix.

---------

Signed-off-by: yijingyan2 <yijingyan@microsoft.com>
Co-authored-by: Sonic Build Admin <sonicbld@microsoft.com>